### ISSUE TITLE
Package installation error: Error: object 'US_stateCodeToName' is not exported by 'namespace:MazamaSpatialUtils'

### ISSUE THREAD

**Issue by DEQygrund** [MazamaScience/RAWSmet#50]
I received this error when installing the package. I am not sure what's wrong here. Could you please let me know what I could do in order to install the package? Thanks!

```
devtools::install_github('MazamaScience/RAWSmet')
Downloading GitHub repo MazamaScience/RAWSmet@HEAD
√  checking for file 'C:\Users\ygrund\AppData\Local\Temp\RtmpaUK4eB\remotes2c1478213bbc\MazamaScience-RAWSmet-bced3ce/DESCRIPTION' ... 
-  preparing 'RAWSmet': (542ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (354ms)
-  checking for empty or unneeded directories
-  building 'RAWSmet_0.2.4.tar.gz'
   
Installing package into ‘C:/Users/ygrund/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'RAWSmet' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error: object 'US_stateCodeToName' is not exported by 'namespace:MazamaSpatialUtils'
Execution halted
ERROR: lazy loading failed for package 'RAWSmet'
* removing 'C:/Users/ygrund/Documents/R/win-library/4.0/RAWSmet'
* restoring previous 'C:/Users/ygrund/Documents/R/win-library/4.0/RAWSmet'
Error: Failed to install 'RAWSmet' from GitHub:
  (converted from warning) installation of package ‘C:/Users/ygrund/AppData/Local/Temp/RtmpaUK4eB/file2c1467275d34/RAWSmet_0.2.4.tar.gz’ had non-zero exit status

```

**Comment by EliGrosman** [comment]
Hi there!

**RAWSmet** relies on the function ```US_stateCodeToName()``` from the [MazamaSpatialUtils](https://github.com/MazamaScience/MazamaSpatialUtils) package. However, this function is currently only available in the version of the package that is on the ```jon``` branch. To install the correct version of this package, run ```devtools::install_github("MazamaScience/MazamaSpatialUtils@jon")```.

It is also important to note that many of **MazamaSpatialUtils**' dependencies are incompatible with Windows. If you encounter any problems installing this package, I would suggest trying again on a Linux or Mac system."

If you need more information on installing **RAWSmet**, the installation information may be found here: https://mazamascience.github.io/RAWSmet/.

We are pleased to be able to develop this package with a GPL-3, open source license and hope that it proves useful. But please use it with a strong **_caveat emptor_**. This package is under active development and is being purpose built for the US Forest Service. The package API may change going forward as per client requests.

**Comment by DEQygrund** [comment]
I appreciate your quick response. Using @jon works for me.

Thanks!

Yuan Grund | Water Quality Analyst | She/Her
Oregon Department of Environmental Quality | Watershed Management
Lloyd 700 Building, 700 NE Multnomah St. Ste. 600, Portland, OR 97232
Email: grund.yuan@deq.state.or.us<mailto:grund.yuan@deq.state.or.us> | Phone: 503.229.6381
